//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spielsücht.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spielsücht.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die v. 1.0.0_b5 (26.03.2019)
        ///NEU:
        ///* Keine Unterstüzung mehr von Windows XP.
        ///VERÄNDERT:
        ///* Man erhält bei der Stufe mittel nun eine Verzinsung von 19 % anstelle von 13 %.
        ///* Kleinere Design Anpassungen.
        ///* Quellcode optimierungen
        ///* Es wird nun kein Hinweis mehr bei dem ersten Programm start angezeigt.
        ///* Der Maximale Einsatz beträgt nun: 9.223.372.036.854.775.807
        ///  * Bei dem Multiplayer spiel bleibt jedoch die maximale Zahl: 2.147.483.647
        ///* Es wird nun .NET Framework 4.5 benötigt.
        ///FIX:
        ///* Sollten die High [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Obwohl dieses Programm ein OpenSource Programm
        ///ist bitte ich darum dises nicht unter dem eigenen
        ///Namen zu veröffentlichen. Solltest du dennoch das
        ///Programm veröffentlichen bitte ich darum darauf
        ///hinzuweisen das nicht du das Programm erstellt hast.
        ///Außerdem bitte ich darum diesen hinweis nicht zu
        ///entfernen und die Über Form nicht zu verändern.
        ///Hälst du dich an diese kleine bitte kannst du das
        ///Spiel so verändern wie du es gerne möchtest.
        ///Danke ähnelt.
        /// </summary>
        public static string Hinweis {
            get {
                return ResourceManager.GetString("Hinweis", resourceCulture);
            }
        }
    }
}
